name: Genera PDF

on:
  push:
    branches: [ main ]
    paths:
      - 'slide/*.*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: generate pdf
      run: | 
        cd slide
        cp 'UX Design.md' 'UX Design-backup.md'
        sed -i "s/%date%/$(date +'%Y-%m-%d')/g" 'UX Design.md'
        sed -i "s/%time%/$(date +'%H:%M')/g" 'UX Design.md'
        npx @marp-team/marp-cli@latest 'UX Design.md' --pdf --allow-local-files --pdf-outlines --pdf-outlines.pages=false
        rm 'UX Design.md'
        mv 'UX Design-backup.md' 'UX Design.md'
        cp 'UX Design domande.md' 'UX Design domande-backup.md'
        sed -i "s/%date%/$(date +'%Y-%m-%d')/g" 'UX Design domande.md'
        sed -i "s/%time%/$(date +'%H:%M')/g" 'UX Design domande.md'
        npx @marp-team/marp-cli@latest 'UX Design domande.md' --pdf --allow-local-files --pdf-outlines --pdf-outlines.pages=false
        rm 'UX Design domande.md'
        mv 'UX Design domande-backup.md' 'UX Design domande.md'
      
    - name: commit & push
      run: |
        git add -A
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "update slides"
        git push
